### ISSUE TITLE
SyntaxError: Invalid key provided - SourceBin#shorten

### ISSUE THREAD

**Issue by sydrinea** [ghostdevv/sourcebin#1]
Upon trying to create a bin using sourcebin#create, I receive an error that an invalid key was provided. 
```error
(node:40713) UnhandledPromiseRejectionWarning: SyntaxError: Invalid key provided - SourceBin#shorten
    at Function.shorten (/Users/<omitted>/Desktop/home/<omitted>/node_modules/sourcebin/src/sourcebin-methods.js:148:59)
    at /Users/<omitted>/Desktop/home/<omitted>/node_modules/sourcebin/src/sourcebin-methods.js:132:33
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:40713) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:40713) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any solution for this?

**Comment by ghostdevv** [comment]
I deployed a fix! Update your dependency to get it
